<?php
    
    return [
        
        "Agaete"                              => __( "Agaete", "ads" ),
        "Agüimes"                             => __( "Agüimes", "ads" ),
        "Antigua"                             => __( "Antigua", "ads" ),
        "Arrecife"                            => __( "Arrecife", "ads" ),
        "Artenara"                            => __( "Artenara", "ads" ),
        "Arucas"                              => __( "Arucas", "ads" ),
        "Betancuria"                          => __( "Betancuria", "ads" ),
        "Firgas"                              => __( "Firgas", "ads" ),
        "Gáldar"                              => __( "Gáldar", "ads" ),
        "Haría"                               => __( "Haría", "ads" ),
        "Ingenio"                             => __( "Ingenio", "ads" ),
        "La Aldea de San Nicolás"             => __( "La Aldea de San Nicolás", "ads" ),
        "La Oliva"                            => __( "La Oliva", "ads" ),
        "Las Palmas de Gran Canaria"          => __( "Las Palmas de Gran Canaria", "ads" ),
        "Mogán"                               => __( "Mogán", "ads" ),
        "Moya"                                => __( "Moya", "ads" ),
        "Puerto del Rosario"                  => __( "Puerto del Rosario", "ads" ),
        "Pájara"                              => __( "Pájara", "ads" ),
        "San Bartolomé"                       => __( "San Bartolomé", "ads" ),
        "San Bartolomé de Tirajana"           => __( "San Bartolomé de Tirajana", "ads" ),
        "Santa Brígida"                       => __( "Santa Brígida", "ads" ),
        "Santa Lucía de Tirajana"             => __( "Santa Lucía de Tirajana", "ads" ),
        "Santa María de Guía de Gran Canaria" => __( "Santa María de Guía de Gran Canaria", "ads" ),
        "Teguise"                             => __( "Teguise", "ads" ),
        "Tejeda"                              => __( "Tejeda", "ads" ),
        "Telde"                               => __( "Telde", "ads" ),
        "Teror"                               => __( "Teror", "ads" ),
        "Tinajo"                              => __( "Tinajo", "ads" ),
        "Tuineje"                             => __( "Tuineje", "ads" ),
        "Tías"                                => __( "Tías", "ads" ),
        "Valleseco"                           => __( "Valleseco", "ads" ),
        "Valsequillo de Gran Canaria"         => __( "Valsequillo de Gran Canaria", "ads" ),
        "Vega de San Mateo"                   => __( "Vega de San Mateo", "ads" ),
        "Yaiza"                               => __( "Yaiza", "ads" ),
        "Other"                               => __( "Other", "ads" ),
    
    ];