<?php
    
    return [
        
        "Abanilla"                  => __( "Abanilla", "ads" ),
        "Abarán"                    => __( "Abarán", "ads" ),
        "Albudeite"                 => __( "Albudeite", "ads" ),
        "Alcantarilla"              => __( "Alcantarilla", "ads" ),
        "Aledo"                     => __( "Aledo", "ads" ),
        "Alguazas"                  => __( "Alguazas", "ads" ),
        "Alhama de Murcia"          => __( "Alhama de Murcia", "ads" ),
        "Archena"                   => __( "Archena", "ads" ),
        "Beniel"                    => __( "Beniel", "ads" ),
        "Blanca"                    => __( "Blanca", "ads" ),
        "Bullas"                    => __( "Bullas", "ads" ),
        "Calasparra"                => __( "Calasparra", "ads" ),
        "Campos del Río"            => __( "Campos del Río", "ads" ),
        "Caravaca de la Cruz"       => __( "Caravaca de la Cruz", "ads" ),
        "Cartagena"                 => __( "Cartagena", "ads" ),
        "Cehegín"                   => __( "Cehegín", "ads" ),
        "Ceutí"                     => __( "Ceutí", "ads" ),
        "Cieza"                     => __( "Cieza", "ads" ),
        "Fortuna"                   => __( "Fortuna", "ads" ),
        "Fuente Álamo de Murcia"    => __( "Fuente Álamo de Murcia", "ads" ),
        "Jumilla"                   => __( "Jumilla", "ads" ),
        "La Unión"                  => __( "La Unión", "ads" ),
        "Las Torres de Cotillas"    => __( "Las Torres de Cotillas", "ads" ),
        "Librilla"                  => __( "Librilla", "ads" ),
        "Lorca"                     => __( "Lorca", "ads" ),
        "Lorquí"                    => __( "Lorquí", "ads" ),
        "Los Alcázares"             => __( "Los Alcázares", "ads" ),
        "Mazarrón"                  => __( "Mazarrón", "ads" ),
        "Molina de Segura"          => __( "Molina de Segura", "ads" ),
        "Moratalla"                 => __( "Moratalla", "ads" ),
        "Mula"                      => __( "Mula", "ads" ),
        "Murcia"                    => __( "Murcia", "ads" ),
        "Ojós"                      => __( "Ojós", "ads" ),
        "Pliego"                    => __( "Pliego", "ads" ),
        "Puerto Lumbreras"          => __( "Puerto Lumbreras", "ads" ),
        "Ricote"                    => __( "Ricote", "ads" ),
        "San Javier"                => __( "San Javier", "ads" ),
        "San Pedro del Pinatar"     => __( "San Pedro del Pinatar", "ads" ),
        "Santomera"                 => __( "Santomera", "ads" ),
        "Torre-Pacheco"             => __( "Torre-Pacheco", "ads" ),
        "Totana"                    => __( "Totana", "ads" ),
        "Ulea"                      => __( "Ulea", "ads" ),
        "Villanueva del Río Segura" => __( "Villanueva del Río Segura", "ads" ),
        "Yecla"                     => __( "Yecla", "ads" ),
        "Águilas"                   => __( "Águilas", "ads" ),
        "Other"                     => __( "Other", "ads" ),
    
    ];