<?php
    
    return [
        
        "Adeje"                      => __( "Adeje", "ads" ),
        "Agulo"                      => __( "Agulo", "ads" ),
        "Alajeró"                    => __( "Alajeró", "ads" ),
        "Arafo"                      => __( "Arafo", "ads" ),
        "Arico"                      => __( "Arico", "ads" ),
        "Arona"                      => __( "Arona", "ads" ),
        "Barlovento"                 => __( "Barlovento", "ads" ),
        "Breña Alta"                 => __( "Breña Alta", "ads" ),
        "Breña Baja"                 => __( "Breña Baja", "ads" ),
        "Buenavista del Norte"       => __( "Buenavista del Norte", "ads" ),
        "Candelaria"                 => __( "Candelaria", "ads" ),
        "El Paso"                    => __( "El Paso", "ads" ),
        "El Pinar de El Hierro"      => __( "El Pinar de El Hierro", "ads" ),
        "El Rosario"                 => __( "El Rosario", "ads" ),
        "El Sauzal"                  => __( "El Sauzal", "ads" ),
        "El Tanque"                  => __( "El Tanque", "ads" ),
        "Fasnia"                     => __( "Fasnia", "ads" ),
        "Frontera"                   => __( "Frontera", "ads" ),
        "Fuencaliente de la Palma"   => __( "Fuencaliente de la Palma", "ads" ),
        "Garachico"                  => __( "Garachico", "ads" ),
        "Garafía"                    => __( "Garafía", "ads" ),
        "Granadilla de Abona"        => __( "Granadilla de Abona", "ads" ),
        "Guía de Isora"              => __( "Guía de Isora", "ads" ),
        "Güímar"                     => __( "Güímar", "ads" ),
        "Hermigua"                   => __( "Hermigua", "ads" ),
        "Icod de los Vinos"          => __( "Icod de los Vinos", "ads" ),
        "La Guancha"                 => __( "La Guancha", "ads" ),
        "La Matanza de Acentejo"     => __( "La Matanza de Acentejo", "ads" ),
        "La Orotava"                 => __( "La Orotava", "ads" ),
        "La Victoria de Acentejo"    => __( "La Victoria de Acentejo", "ads" ),
        "Los Llanos de Aridane"      => __( "Los Llanos de Aridane", "ads" ),
        "Los Realejos"               => __( "Los Realejos", "ads" ),
        "Los Silos"                  => __( "Los Silos", "ads" ),
        "Puerto de la Cruz"          => __( "Puerto de la Cruz", "ads" ),
        "Puntagorda"                 => __( "Puntagorda", "ads" ),
        "Puntallana"                 => __( "Puntallana", "ads" ),
        "San Andrés y Sauces"        => __( "San Andrés y Sauces", "ads" ),
        "San Cristóbal de La Laguna" => __( "San Cristóbal de La Laguna", "ads" ),
        "San Juan de la Rambla"      => __( "San Juan de la Rambla", "ads" ),
        "San Miguel de Abona"        => __( "San Miguel de Abona", "ads" ),
        "San Sebastián de la Gomera" => __( "San Sebastián de la Gomera", "ads" ),
        "Santa Cruz de Tenerife"     => __( "Santa Cruz de Tenerife", "ads" ),
        "Santa Cruz de la Palma"     => __( "Santa Cruz de la Palma", "ads" ),
        "Santa Úrsula"               => __( "Santa Úrsula", "ads" ),
        "Santiago del Teide"         => __( "Santiago del Teide", "ads" ),
        "Tacoronte"                  => __( "Tacoronte", "ads" ),
        "Tazacorte"                  => __( "Tazacorte", "ads" ),
        "Tegueste"                   => __( "Tegueste", "ads" ),
        "Tijarafe"                   => __( "Tijarafe", "ads" ),
        "Valle Gran Rey"             => __( "Valle Gran Rey", "ads" ),
        "Vallehermoso"               => __( "Vallehermoso", "ads" ),
        "Valverde"                   => __( "Valverde", "ads" ),
        "Vilaflor de Chasna"         => __( "Vilaflor de Chasna", "ads" ),
        "Villa de Mazo"              => __( "Villa de Mazo", "ads" ),
        "Other"                      => __( "Other", "ads" ),
    
    ];