<?php
    
    return [
        
        "Aalten"            => __( "Aalten", "ads" ),
        "Apeldoorn"         => __( "Apeldoorn", "ads" ),
        "Arnhem"            => __( "Arnhem", "ads" ),
        "Barneveld"         => __( "Barneveld", "ads" ),
        "Berg en Dal"       => __( "Berg en Dal", "ads" ),
        "Berkelland"        => __( "Berkelland", "ads" ),
        "Beuningen"         => __( "Beuningen", "ads" ),
        "Bronckhorst"       => __( "Bronckhorst", "ads" ),
        "Brummen"           => __( "Brummen", "ads" ),
        "Buren"             => __( "Buren", "ads" ),
        "Culemborg"         => __( "Culemborg", "ads" ),
        "Doesburg"          => __( "Doesburg", "ads" ),
        "Doetinchem"        => __( "Doetinchem", "ads" ),
        "Druten"            => __( "Druten", "ads" ),
        "Duiven"            => __( "Duiven", "ads" ),
        "Ede"               => __( "Ede", "ads" ),
        "Elburg"            => __( "Elburg", "ads" ),
        "Epe"               => __( "Epe", "ads" ),
        "Ermelo"            => __( "Ermelo", "ads" ),
        "Geldermalsen"      => __( "Geldermalsen", "ads" ),
        "Harderwijk"        => __( "Harderwijk", "ads" ),
        "Hattem"            => __( "Hattem", "ads" ),
        "Heerde"            => __( "Heerde", "ads" ),
        "Heumen"            => __( "Heumen", "ads" ),
        "Lingewaal"         => __( "Lingewaal", "ads" ),
        "Lingewaard"        => __( "Lingewaard", "ads" ),
        "Lochem"            => __( "Lochem", "ads" ),
        "Maasdriel"         => __( "Maasdriel", "ads" ),
        "Montferland"       => __( "Montferland", "ads" ),
        "Neder-Betuwe"      => __( "Neder-Betuwe", "ads" ),
        "Neerijnen"         => __( "Neerijnen", "ads" ),
        "Nijkerk"           => __( "Nijkerk", "ads" ),
        "Nijmegen"          => __( "Nijmegen", "ads" ),
        "Nunspeet"          => __( "Nunspeet", "ads" ),
        "Oldebroek"         => __( "Oldebroek", "ads" ),
        "Oost Gelre"        => __( "Oost Gelre", "ads" ),
        "Oude Ijsselstreek" => __( "Oude Ijsselstreek", "ads" ),
        "Overbetuwe"        => __( "Overbetuwe", "ads" ),
        "Putten"            => __( "Putten", "ads" ),
        "Renkum"            => __( "Renkum", "ads" ),
        "Rheden"            => __( "Rheden", "ads" ),
        "Rijnwaarden"       => __( "Rijnwaarden", "ads" ),
        "Rozendaal"         => __( "Rozendaal", "ads" ),
        "Scherpenzeel"      => __( "Scherpenzeel", "ads" ),
        "Tiel"              => __( "Tiel", "ads" ),
        "Voorst"            => __( "Voorst", "ads" ),
        "Wageningen"        => __( "Wageningen", "ads" ),
        "West Maas en Waal" => __( "West Maas en Waal", "ads" ),
        "Westervoort"       => __( "Westervoort", "ads" ),
        "Wijchen"           => __( "Wijchen", "ads" ),
        "Winterswijk"       => __( "Winterswijk", "ads" ),
        "Zaltbommel"        => __( "Zaltbommel", "ads" ),
        "Zevenaar"          => __( "Zevenaar", "ads" ),
        "Zutphen"           => __( "Zutphen", "ads" ),
        "Other"             => __( "Other", "ads" ),
    
    ];