<?php
    
    return [
        
        "Beek"                   => __( "Beek", "ads" ),
        "Beesel"                 => __( "Beesel", "ads" ),
        "Bergen"                 => __( "Bergen", "ads" ),
        "Brunssum"               => __( "Brunssum", "ads" ),
        "Echt-Susteren"          => __( "Echt-Susteren", "ads" ),
        "Eijsden-Margraten"      => __( "Eijsden-Margraten", "ads" ),
        "Gennep"                 => __( "Gennep", "ads" ),
        "Gulpen-Wittem"          => __( "Gulpen-Wittem", "ads" ),
        "Heerlen"                => __( "Heerlen", "ads" ),
        "Helden"                 => __( "Helden", "ads" ),
        "Horst aan de Maas"      => __( "Horst aan de Maas", "ads" ),
        "Kerkrade"               => __( "Kerkrade", "ads" ),
        "Landgraaf"              => __( "Landgraaf", "ads" ),
        "Leudal"                 => __( "Leudal", "ads" ),
        "Maasbree"               => __( "Maasbree", "ads" ),
        "Maasgouw"               => __( "Maasgouw", "ads" ),
        "Maastricht"             => __( "Maastricht", "ads" ),
        "Meerssen"               => __( "Meerssen", "ads" ),
        "Meijel"                 => __( "Meijel", "ads" ),
        "Mook en Middelaar"      => __( "Mook en Middelaar", "ads" ),
        "Nederweert"             => __( "Nederweert", "ads" ),
        "Nuth"                   => __( "Nuth", "ads" ),
        "Onderbanken"            => __( "Onderbanken", "ads" ),
        "Peel en Maas"           => __( "Peel en Maas", "ads" ),
        "Roerdalen"              => __( "Roerdalen", "ads" ),
        "Roermond"               => __( "Roermond", "ads" ),
        "Schinnen"               => __( "Schinnen", "ads" ),
        "Sevenum"                => __( "Sevenum", "ads" ),
        "Simpelveld"             => __( "Simpelveld", "ads" ),
        "Sittard-Geleen"         => __( "Sittard-Geleen", "ads" ),
        "Stein"                  => __( "Stein", "ads" ),
        "Vaals"                  => __( "Vaals", "ads" ),
        "Valkenburg aan de Geul" => __( "Valkenburg aan de Geul", "ads" ),
        "Venlo"                  => __( "Venlo", "ads" ),
        "Venray"                 => __( "Venray", "ads" ),
        "Voerendaal"             => __( "Voerendaal", "ads" ),
        "Weert"                  => __( "Weert", "ads" ),
        "Other"                  => __( "Other", "ads" ),
    
    ];