<?php
    
    return [
        
        "Aalsmeer"       => __( "Aalsmeer", "ads" ),
        "Alkmaar"        => __( "Alkmaar", "ads" ),
        "Amstelveen"     => __( "Amstelveen", "ads" ),
        "Amsterdam"      => __( "Amsterdam", "ads" ),
        "Beemster"       => __( "Beemster", "ads" ),
        "Bergen"         => __( "Bergen", "ads" ),
        "Beverwijk"      => __( "Beverwijk", "ads" ),
        "Blaricum"       => __( "Blaricum", "ads" ),
        "Bloemendaal"    => __( "Bloemendaal", "ads" ),
        "Castricum"      => __( "Castricum", "ads" ),
        "Den Helder"     => __( "Den Helder", "ads" ),
        "Diemen"         => __( "Diemen", "ads" ),
        "Drechterland"   => __( "Drechterland", "ads" ),
        "Edam-Volendam"  => __( "Edam-Volendam", "ads" ),
        "Enkhuizen"      => __( "Enkhuizen", "ads" ),
        "Gooise Meren"   => __( "Gooise Meren", "ads" ),
        "Haarlem"        => __( "Haarlem", "ads" ),
        "Haarlemmermeer" => __( "Haarlemmermeer", "ads" ),
        "Heemskerk"      => __( "Heemskerk", "ads" ),
        "Heemstede"      => __( "Heemstede", "ads" ),
        "Heerhugowaard"  => __( "Heerhugowaard", "ads" ),
        "Heiloo"         => __( "Heiloo", "ads" ),
        "Hilversum"      => __( "Hilversum", "ads" ),
        "Hollands Kroon" => __( "Hollands Kroon", "ads" ),
        "Hoorn"          => __( "Hoorn", "ads" ),
        "Huizen"         => __( "Huizen", "ads" ),
        "Koggenland"     => __( "Koggenland", "ads" ),
        "Landsmeer"      => __( "Landsmeer", "ads" ),
        "Langedijk"      => __( "Langedijk", "ads" ),
        "Laren"          => __( "Laren", "ads" ),
        "Medemblik"      => __( "Medemblik", "ads" ),
        "Nieuwkoop"      => __( "Nieuwkoop", "ads" ),
        "Oostzaan"       => __( "Oostzaan", "ads" ),
        "Opmeer"         => __( "Opmeer", "ads" ),
        "Ouder-Amstel"   => __( "Ouder-Amstel", "ads" ),
        "Purmerend"      => __( "Purmerend", "ads" ),
        "Schagen"        => __( "Schagen", "ads" ),
        "Stede Broec"    => __( "Stede Broec", "ads" ),
        "Texel"          => __( "Texel", "ads" ),
        "Uitgeest"       => __( "Uitgeest", "ads" ),
        "Uithoorn"       => __( "Uithoorn", "ads" ),
        "Velsen"         => __( "Velsen", "ads" ),
        "Waterland"      => __( "Waterland", "ads" ),
        "Weesp"          => __( "Weesp", "ads" ),
        "Wijdemeren"     => __( "Wijdemeren", "ads" ),
        "Wormerland"     => __( "Wormerland", "ads" ),
        "Zaanstad"       => __( "Zaanstad", "ads" ),
        "Zandvoort"      => __( "Zandvoort", "ads" ),
        "Other"          => __( "Other", "ads" ),
    
    ];