<?php
    
    return [
        
        "Alblasserdam"           => __( "Alblasserdam", "ads" ),
        "Albrandswaard"          => __( "Albrandswaard", "ads" ),
        "Alphen aan den Rijn"    => __( "Alphen aan den Rijn", "ads" ),
        "Barendrecht"            => __( "Barendrecht", "ads" ),
        "Binnenmaas"             => __( "Binnenmaas", "ads" ),
        "Bodegraven-Reeuwijk"    => __( "Bodegraven-Reeuwijk", "ads" ),
        "Brielle"                => __( "Brielle", "ads" ),
        "Capelle aan den IJssel" => __( "Capelle aan den IJssel", "ads" ),
        "Cromstrijen"            => __( "Cromstrijen", "ads" ),
        "Delft"                  => __( "Delft", "ads" ),
        "Den Haag"               => __( "Den Haag", "ads" ),
        "Dordrecht"              => __( "Dordrecht", "ads" ),
        "Giessenlanden"          => __( "Giessenlanden", "ads" ),
        "Goeree-Overflakkee"     => __( "Goeree-Overflakkee", "ads" ),
        "Gorinchem"              => __( "Gorinchem", "ads" ),
        "Gouda"                  => __( "Gouda", "ads" ),
        "Hardinxveld-Giessendam" => __( "Hardinxveld-Giessendam", "ads" ),
        "Hellevoetsluis"         => __( "Hellevoetsluis", "ads" ),
        "Hendrik-Ido-Ambacht"    => __( "Hendrik-Ido-Ambacht", "ads" ),
        "Hillegom"               => __( "Hillegom", "ads" ),
        "Kaag en Braassem"       => __( "Kaag en Braassem", "ads" ),
        "Katwijk"                => __( "Katwijk", "ads" ),
        "Korendijk"              => __( "Korendijk", "ads" ),
        "Krimpen aan den IJssel" => __( "Krimpen aan den IJssel", "ads" ),
        "Krimpenerwaard"         => __( "Krimpenerwaard", "ads" ),
        "Lansingerland"          => __( "Lansingerland", "ads" ),
        "Leiden"                 => __( "Leiden", "ads" ),
        "Leiderdorp"             => __( "Leiderdorp", "ads" ),
        "Leidschendam-Voorburg"  => __( "Leidschendam-Voorburg", "ads" ),
        "Lisse"                  => __( "Lisse", "ads" ),
        "Maassluis"              => __( "Maassluis", "ads" ),
        "Midden-Delfland"        => __( "Midden-Delfland", "ads" ),
        "Molenlanden"            => __( "Molenlanden", "ads" ),
        "Nieuwkoop"              => __( "Nieuwkoop", "ads" ),
        "Nissewaard"             => __( "Nissewaard", "ads" ),
        "Noordwijk"              => __( "Noordwijk", "ads" ),
        "Oegstgeest"             => __( "Oegstgeest", "ads" ),
        "Oud-Beijerland"         => __( "Oud-Beijerland", "ads" ),
        "Papendrecht"            => __( "Papendrecht", "ads" ),
        "Pijnacker-Nootdorp"     => __( "Pijnacker-Nootdorp", "ads" ),
        "Ridderkerk"             => __( "Ridderkerk", "ads" ),
        "Rijswijk"               => __( "Rijswijk", "ads" ),
        "Rotterdam"              => __( "Rotterdam", "ads" ),
        "Schiedam"               => __( "Schiedam", "ads" ),
        "Sliedrecht"             => __( "Sliedrecht", "ads" ),
        "Strijen"                => __( "Strijen", "ads" ),
        "Teylingen"              => __( "Teylingen", "ads" ),
        "Vlaardingen"            => __( "Vlaardingen", "ads" ),
        "Voorschoten"            => __( "Voorschoten", "ads" ),
        "Waddinxveen"            => __( "Waddinxveen", "ads" ),
        "Wassenaar"              => __( "Wassenaar", "ads" ),
        "Westland"               => __( "Westland", "ads" ),
        "Westvoorne"             => __( "Westvoorne", "ads" ),
        "Zoetermeer"             => __( "Zoetermeer", "ads" ),
        "Zoeterwoude"            => __( "Zoeterwoude", "ads" ),
        "Zuidplas"               => __( "Zuidplas", "ads" ),
        "Zwijndrecht"            => __( "Zwijndrecht", "ads" ),
        "Other"                  => __( "Other", "ads" ),
    
    ];