<?php
    
    return [
        
        "Abu Shagara" => __( "Abu Shagara", "ads" ),
        "Al Azrah"    => __( "Al Azrah", "ads" ),
        "Al Fahiya"   => __( "Al Fahiya", "ads" ),
        "Al Falaj"    => __( "Al Falaj", "ads" ),
        "Al Hamriyah" => __( "Al Hamriyah", "ads" ),
        "Al Khan"     => __( "Al Khan", "ads" ),
        "Al Khashfah" => __( "Al Khashfah", "ads" ),
        "Al Manak"    => __( "Al Manak", "ads" ),
        "Al Qazimiya" => __( "Al Qazimiya", "ads" ),
        "Al Rafa'ah"  => __( "Al Rafa'ah", "ads" ),
        "Al Tawoon"   => __( "Al Tawoon", "ads" ),
        "Al Wasit"    => __( "Al Wasit", "ads" ),
        "Badiyah"     => __( "Badiyah", "ads" ),
        "Buteena"     => __( "Buteena", "ads" ),
        "Dasman"      => __( "Dasman", "ads" ),
        "Dhaid"       => __( "Dhaid", "ads" ),
        "Ghafia"      => __( "Ghafia", "ads" ),
        "Ghubaiba"    => __( "Ghubaiba", "ads" ),
        "Hamariya"    => __( "Hamariya", "ads" ),
        "Jazzat"      => __( "Jazzat", "ads" ),
        "Khannur"     => __( "Khannur", "ads" ),
        "Kharayan"    => __( "Kharayan", "ads" ),
        "Layyah"      => __( "Layyah", "ads" ),
        "Maisaloon"   => __( "Maisaloon", "ads" ),
        "Majjarah"    => __( "Majjarah", "ads" ),
        "Mansoora"    => __( "Mansoora", "ads" ),
        "Muwafja"     => __( "Muwafja", "ads" ),
        "Nabbah"      => __( "Nabbah", "ads" ),
        "Nakheelat"   => __( "Nakheelat", "ads" ),
        "Nasariya"    => __( "Nasariya", "ads" ),
        "Qasimiya"    => __( "Qasimiya", "ads" ),
        "Ramaqiya"    => __( "Ramaqiya", "ads" ),
        "Ramlah"      => __( "Ramlah", "ads" ),
        "Ramtha"      => __( "Ramtha", "ads" ),
        "Rolla"       => __( "Rolla", "ads" ),
        "Saabah"      => __( "Saabah", "ads" ),
        "Saif"        => __( "Saif", "ads" ),
        "Samnan"      => __( "Samnan", "ads" ),
        "Shahba"      => __( "Shahba", "ads" ),
        "Sharjah"     => __( "Sharjah", "ads" ),
        "Sherqan"     => __( "Sherqan", "ads" ),
        "Umm Kanoor"  => __( "Umm Kanoor", "ads" ),
        "Wadi Shi"    => __( "Wadi Shi", "ads" ),
        "Wasit"       => __( "Wasit", "ads" ),
        "Yarmook"     => __( "Yarmook", "ads" ),
        "Other"       => __( "Other", "ads" ),
    
    ];