<?php
    
    return [
        
        "Apostolivskyi"      => __( "Apostolivskyi", "ads" ),
        "Dnipro"             => __( "Dnipro", "ads" ),
        "Dniprodzerzhynsk"   => __( "Dniprodzerzhynsk", "ads" ),
        "Dnipropetrovsk"     => __( "Dnipropetrovsk", "ads" ),
        "Dnipropetrovskyi"   => __( "Dnipropetrovskyi", "ads" ),
        "Dniprovskyi"        => __( "Dniprovskyi", "ads" ),
        "Kamyanske"          => __( "Kamyanske", "ads" ),
        "Krynychanskyi"      => __( "Krynychanskyi", "ads" ),
        "Kryvorizkyi"        => __( "Kryvorizkyi", "ads" ),
        "Kryvyi Rih"         => __( "Kryvyi Rih", "ads" ),
        "Mahdalynivskyi"     => __( "Mahdalynivskyi", "ads" ),
        "Marhanets"          => __( "Marhanets", "ads" ),
        "Mezhivskyi"         => __( "Mezhivskyi", "ads" ),
        "Nikopol"            => __( "Nikopol", "ads" ),
        "Nikopolskyi"        => __( "Nikopolskyi", "ads" ),
        "Novomoskovsk"       => __( "Novomoskovsk", "ads" ),
        "Novomoskovskyi"     => __( "Novomoskovskyi", "ads" ),
        "Ordzhonikidze"      => __( "Ordzhonikidze", "ads" ),
        "Pavlohrad"          => __( "Pavlohrad", "ads" ),
        "Pavlohradskyi"      => __( "Pavlohradskyi", "ads" ),
        "Pershotravensk"     => __( "Pershotravensk", "ads" ),
        "Petropavlivskyi"    => __( "Petropavlivskyi", "ads" ),
        "Petrykivskyi"       => __( "Petrykivskyi", "ads" ),
        "Piatykhatskyi"      => __( "Piatykhatskyi", "ads" ),
        "Piatykhatskyi"      => __( "Piatykhatskyi", "ads" ),
        "Pokrov"             => __( "Pokrov", "ads" ),
        "Pokrovskyi"         => __( "Pokrovskyi", "ads" ),
        "Shyrokivskyi"       => __( "Shyrokivskyi", "ads" ),
        "Sofiivskyi"         => __( "Sofiivskyi", "ads" ),
        "Solonianskyi"       => __( "Solonianskyi", "ads" ),
        "Synelnykivskyi"     => __( "Synelnykivskyi", "ads" ),
        "Synelnykove"        => __( "Synelnykove", "ads" ),
        "Ternivka"           => __( "Ternivka", "ads" ),
        "Tomakivskyi"        => __( "Tomakivskyi", "ads" ),
        "Tsarychanskyi"      => __( "Tsarychanskyi", "ads" ),
        "Vasylkivskyi"       => __( "Vasylkivskyi", "ads" ),
        "Verkhnodniprovskyi" => __( "Verkhnodniprovskyi", "ads" ),
        "Vilnohirsk"         => __( "Vilnohirsk", "ads" ),
        "Yurivskyi"          => __( "Yurivskyi", "ads" ),
        "Zhovti Vody"        => __( "Zhovti Vody", "ads" ),
        "Other"              => __( "Other", "ads" ),
    
    ];