<?php
    
    return [
        
        "Piatykhatskyi"        => __( "Piatykhatskyi", "ads" ),
        "Amvrosiivskyi"        => __( "Amvrosiivskyi", "ads" ),
        "Artemivsk"            => __( "Artemivsk", "ads" ),
        "Artemivskyi"          => __( "Artemivskyi", "ads" ),
        "Avdiivka"             => __( "Avdiivka", "ads" ),
        "Chistiykove"          => __( "Chistiykove", "ads" ),
        "Debaltseve"           => __( "Debaltseve", "ads" ),
        "Dobropillia"          => __( "Dobropillia", "ads" ),
        "Dobropilskyi"         => __( "Dobropilskyi", "ads" ),
        "Dokuchaievsk"         => __( "Dokuchaievsk", "ads" ),
        "Donetsk"              => __( "Donetsk", "ads" ),
        "Druzhkivka"           => __( "Druzhkivka", "ads" ),
        "Dymytrov"             => __( "Dymytrov", "ads" ),
        "Dzerzhynsk"           => __( "Dzerzhynsk", "ads" ),
        "Horlivka"             => __( "Horlivka", "ads" ),
        "Hrestivka"            => __( "Hrestivka", "ads" ),
        "Khartsyzk"            => __( "Khartsyzk", "ads" ),
        "Kirovske"             => __( "Kirovske", "ads" ),
        "Kostiantynivka"       => __( "Kostiantynivka", "ads" ),
        "Kostiantynivskyi"     => __( "Kostiantynivskyi", "ads" ),
        "Kramatorsk"           => __( "Kramatorsk", "ads" ),
        "Krasnoarmiyskyi"      => __( "Krasnoarmiyskyi", "ads" ),
        "Krasnolymanskyi"      => __( "Krasnolymanskyi", "ads" ),
        "Krasnyi Lyman"        => __( "Krasnyi Lyman", "ads" ),
        "Makiivka"             => __( "Makiivka", "ads" ),
        "Marinskyi"            => __( "Marinskyi", "ads" ),
        "Marinskyi"            => __( "Marinskyi", "ads" ),
        "Mariupol"             => __( "Mariupol", "ads" ),
        "Mirnograd"            => __( "Mirnograd", "ads" ),
        "Novoazovskyi"         => __( "Novoazovskyi", "ads" ),
        "Novohrodivka"         => __( "Novohrodivka", "ads" ),
        "Oleksandrivskyi"      => __( "Oleksandrivskyi", "ads" ),
        "Pershotravnevyi"      => __( "Pershotravnevyi", "ads" ),
        "Pokrovsk"             => __( "Pokrovsk", "ads" ),
        "Pokrovskiy"           => __( "Pokrovskiy", "ads" ),
        "Selydove"             => __( "Selydove", "ads" ),
        "Shakhtarsk"           => __( "Shakhtarsk", "ads" ),
        "Shakhtarskyi"         => __( "Shakhtarskyi", "ads" ),
        "Sloviansk"            => __( "Sloviansk", "ads" ),
        "Slovianskyi"          => __( "Slovianskyi", "ads" ),
        "Snizhne"              => __( "Snizhne", "ads" ),
        "Starobeshivskyi"      => __( "Starobeshivskyi", "ads" ),
        "Telmanivskyi"         => __( "Telmanivskyi", "ads" ),
        "Toretsk"              => __( "Toretsk", "ads" ),
        "Torez"                => __( "Torez", "ads" ),
        "Velykonovosilkivskyi" => __( "Velykonovosilkivskyi", "ads" ),
        "Volnovaskyi"          => __( "Volnovaskyi", "ads" ),
        "Volodarskyi"          => __( "Volodarskyi", "ads" ),
        "Vuhledar"             => __( "Vuhledar", "ads" ),
        "Yasynuvata"           => __( "Yasynuvata", "ads" ),
        "Yasynuvatskyi"        => __( "Yasynuvatskyi", "ads" ),
        "Yenakiyeve"           => __( "Yenakiyeve", "ads" ),
        "Zhdanivka"            => __( "Zhdanivka", "ads" ),
        "Other"                => __( "Other", "ads" ),
    
    ];