<?php
    
    return [
        
        "Piatykhatskyi"     => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"         => __( "Marinskyi", "ads" ),
        "Balakliiskyi"      => __( "Balakliiskyi", "ads" ),
        "Barvinkivskyi"     => __( "Barvinkivskyi", "ads" ),
        "Blyzniukivskyi"    => __( "Blyzniukivskyi", "ads" ),
        "Bohodukhivskyi"    => __( "Bohodukhivskyi", "ads" ),
        "Borivskyi"         => __( "Borivskyi", "ads" ),
        "Chuhuiv"           => __( "Chuhuiv", "ads" ),
        "Chuhuivskyi"       => __( "Chuhuivskyi", "ads" ),
        "Derhachivskyi"     => __( "Derhachivskyi", "ads" ),
        "Dvorichanskyi"     => __( "Dvorichanskyi", "ads" ),
        "Izium"             => __( "Izium", "ads" ),
        "Iziumskyi"         => __( "Iziumskyi", "ads" ),
        "Kehychivskyi"      => __( "Kehychivskyi", "ads" ),
        "Kharkiv"           => __( "Kharkiv", "ads" ),
        "Kharkivskyi"       => __( "Kharkivskyi", "ads" ),
        "Kolomatskyi"       => __( "Kolomatskyi", "ads" ),
        "Krasnohradskyi"    => __( "Krasnohradskyi", "ads" ),
        "Krasnokutskyi"     => __( "Krasnokutskyi", "ads" ),
        "Kupiansk"          => __( "Kupiansk", "ads" ),
        "Kupianskyi"        => __( "Kupianskyi", "ads" ),
        "Kupianskyi"        => __( "Kupianskyi", "ads" ),
        "Kupyansk"          => __( "Kupyansk", "ads" ),
        "Liubotyn"          => __( "Liubotyn", "ads" ),
        "Lozivskyi"         => __( "Lozivskyi", "ads" ),
        "Lozova"            => __( "Lozova", "ads" ),
        "Novovodolazkyi"    => __( "Novovodolazkyi", "ads" ),
        "Pechenizkyi"       => __( "Pechenizkyi", "ads" ),
        "Pervomaiskyi"      => __( "Pervomaiskyi", "ads" ),
        "Sakhnovshchynskyi" => __( "Sakhnovshchynskyi", "ads" ),
        "Shevchenkivskyi"   => __( "Shevchenkivskyi", "ads" ),
        "Valkivskyi"        => __( "Valkivskyi", "ads" ),
        "Velykoburlutskyi"  => __( "Velykoburlutskyi", "ads" ),
        "Vovchanskyi"       => __( "Vovchanskyi", "ads" ),
        "Zachepylivskyi"    => __( "Zachepylivskyi", "ads" ),
        "Zmiivskyi"         => __( "Zmiivskyi", "ads" ),
        "Zolochivskyi"      => __( "Zolochivskyi", "ads" ),
        "Other"             => __( "Other", "ads" ),
    
    ];