<?php
    
    return [
        
        "Piatykhatskyi"         => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"             => __( "Marinskyi", "ads" ),
        "Kupianskyi"            => __( "Kupianskyi", "ads" ),
        "Bilohirskyi"           => __( "Bilohirskyi", "ads" ),
        "Chemerovetskyi"        => __( "Chemerovetskyi", "ads" ),
        "Derazhnianskyi"        => __( "Derazhnianskyi", "ads" ),
        "Dunaievetskyi"         => __( "Dunaievetskyi", "ads" ),
        "Horodotskyi"           => __( "Horodotskyi", "ads" ),
        "Iziaslavskyi"          => __( "Iziaslavskyi", "ads" ),
        "Kamianets-Podilskyi"   => __( "Kamianets-Podilskyi", "ads" ),
        "Kamianets-podilskyi"   => __( "Kamianets-podilskyi", "ads" ),
        "Khmelnytskyi"          => __( "Khmelnytskyi", "ads" ),
        "Khmelnytskyi"          => __( "Khmelnytskyi", "ads" ),
        "Krasylivskyi"          => __( "Krasylivskyi", "ads" ),
        "Letychivskyi"          => __( "Letychivskyi", "ads" ),
        "Netishyn"              => __( "Netishyn", "ads" ),
        "Novoushytskyi"         => __( "Novoushytskyi", "ads" ),
        "Polonskyi"             => __( "Polonskyi", "ads" ),
        "Shepetivka"            => __( "Shepetivka", "ads" ),
        "Shepetivskyi"          => __( "Shepetivskyi", "ads" ),
        "Slavuta"               => __( "Slavuta", "ads" ),
        "Slavutskyi"            => __( "Slavutskyi", "ads" ),
        "Starokostiantyniv"     => __( "Starokostiantyniv", "ads" ),
        "Starokostiantynivskyi" => __( "Starokostiantynivskyi", "ads" ),
        "Starosyniavskyi"       => __( "Starosyniavskyi", "ads" ),
        "Teofipolskyi"          => __( "Teofipolskyi", "ads" ),
        "Vinkovetskyi"          => __( "Vinkovetskyi", "ads" ),
        "Volochyskyi"           => __( "Volochyskyi", "ads" ),
        "Yarmolynetskyi"        => __( "Yarmolynetskyi", "ads" ),
        "Other"                 => __( "Other", "ads" ),
    
    ];