<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Baryshivskyi"            => __( "Baryshivskyi", "ads" ),
        "Berezan"                 => __( "Berezan", "ads" ),
        "Bila Tserkva"            => __( "Bila Tserkva", "ads" ),
        "Bilotserkivskyi"         => __( "Bilotserkivskyi", "ads" ),
        "Bohuslavskyi"            => __( "Bohuslavskyi", "ads" ),
        "Borodianskyi"            => __( "Borodianskyi", "ads" ),
        "Boryspil"                => __( "Boryspil", "ads" ),
        "Boryspilskyi"            => __( "Boryspilskyi", "ads" ),
        "Brovarskyi"              => __( "Brovarskyi", "ads" ),
        "Brovary"                 => __( "Brovary", "ads" ),
        "Bucha"                   => __( "Bucha", "ads" ),
        "Fastiv"                  => __( "Fastiv", "ads" ),
        "Fastivskyi"              => __( "Fastivskyi", "ads" ),
        "Irpin"                   => __( "Irpin", "ads" ),
        "Ivankivskyi"             => __( "Ivankivskyi", "ads" ),
        "Kaharlytskyi"            => __( "Kaharlytskyi", "ads" ),
        "Kyievo-Sviatoshynskyi"   => __( "Kyievo-Sviatoshynskyi", "ads" ),
        "Makarivskyi"             => __( "Makarivskyi", "ads" ),
        "Myronivskyi"             => __( "Myronivskyi", "ads" ),
        "Obukhiv"                 => __( "Obukhiv", "ads" ),
        "Obukhivskyi"             => __( "Obukhivskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Poliskyi"                => __( "Poliskyi", "ads" ),
        "Rokytnianskyi"           => __( "Rokytnianskyi", "ads" ),
        "Rzhyshchiv"              => __( "Rzhyshchiv", "ads" ),
        "Skvyrskyi"               => __( "Skvyrskyi", "ads" ),
        "Slavutych"               => __( "Slavutych", "ads" ),
        "Stavyshchenskyi"         => __( "Stavyshchenskyi", "ads" ),
        "Tarashchanskyi"          => __( "Tarashchanskyi", "ads" ),
        "Tetiivskyi"              => __( "Tetiivskyi", "ads" ),
        "Vasylkiv"                => __( "Vasylkiv", "ads" ),
        "Vasylkivskyi"            => __( "Vasylkivskyi", "ads" ),
        "Volodarskyi"             => __( "Volodarskyi", "ads" ),
        "Vyshhorodskyi"           => __( "Vyshhorodskyi", "ads" ),
        "Yahotynskyi"             => __( "Yahotynskyi", "ads" ),
        "Zhurivskyi"              => __( "Zhurivskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];