<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Alchevsk"                => __( "Alchevsk", "ads" ),
        "Antratsyt"               => __( "Antratsyt", "ads" ),
        "Antratsytivskyi"         => __( "Antratsytivskyi", "ads" ),
        "Bilokurakynskyi"         => __( "Bilokurakynskyi", "ads" ),
        "Bilovodskyi"             => __( "Bilovodskyi", "ads" ),
        "Brianka"                 => __( "Brianka", "ads" ),
        "Dovjanskyi"              => __( "Dovjanskyi", "ads" ),
        "Khrustalnyi"             => __( "Khrustalnyi", "ads" ),
        "Kirovsk"                 => __( "Kirovsk", "ads" ),
        "Krasnodon"               => __( "Krasnodon", "ads" ),
        "Krasnodonskyi"           => __( "Krasnodonskyi", "ads" ),
        "Krasnyi Luch"            => __( "Krasnyi Luch", "ads" ),
        "Kreminna"                => __( "Kreminna", "ads" ),
        "Kreminskyi"              => __( "Kreminskyi", "ads" ),
        "Luhansk"                 => __( "Luhansk", "ads" ),
        "Lutuhynskyi"             => __( "Lutuhynskyi", "ads" ),
        "Lysychansk"              => __( "Lysychansk", "ads" ),
        "Markivskyi"              => __( "Markivskyi", "ads" ),
        "Milovskyi"               => __( "Milovskyi", "ads" ),
        "Novoaidarskyi"           => __( "Novoaidarskyi", "ads" ),
        "Novopskovskyi"           => __( "Novopskovskyi", "ads" ),
        "Perevalskyi"             => __( "Perevalskyi", "ads" ),
        "Pervomaisk"              => __( "Pervomaisk", "ads" ),
        "Popasnianskyi"           => __( "Popasnianskyi", "ads" ),
        "Rovenky"                 => __( "Rovenky", "ads" ),
        "Rubizhne"                => __( "Rubizhne", "ads" ),
        "Sievierodonetsk"         => __( "Sievierodonetsk", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Sorokinskyi"             => __( "Sorokinskyi", "ads" ),
        "Stakhanov"               => __( "Stakhanov", "ads" ),
        "Stanychno-Luhanskyi"     => __( "Stanychno-Luhanskyi", "ads" ),
        "Starobilskyi"            => __( "Starobilskyi", "ads" ),
        "Svativskyi"              => __( "Svativskyi", "ads" ),
        "Sverdlovsk"              => __( "Sverdlovsk", "ads" ),
        "Sverdlovskyi"            => __( "Sverdlovskyi", "ads" ),
        "Troitskyi"               => __( "Troitskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];