<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Boryslav"                => __( "Boryslav", "ads" ),
        "Brodivskyi"              => __( "Brodivskyi", "ads" ),
        "Buskyi"                  => __( "Buskyi", "ads" ),
        "Chervonohrad"            => __( "Chervonohrad", "ads" ),
        "Drohobych"               => __( "Drohobych", "ads" ),
        "Drohobytskyi"            => __( "Drohobytskyi", "ads" ),
        "Horodotskyi"             => __( "Horodotskyi", "ads" ),
        "Kamianka-Buzkyi"         => __( "Kamianka-Buzkyi", "ads" ),
        "Kamianka-buzkyi"         => __( "Kamianka-buzkyi", "ads" ),
        "Lviv"                    => __( "Lviv", "ads" ),
        "Morshyn"                 => __( "Morshyn", "ads" ),
        "Mostyskyi"               => __( "Mostyskyi", "ads" ),
        "Mykolaivskyi"            => __( "Mykolaivskyi", "ads" ),
        "Novyi Rozdil"            => __( "Novyi Rozdil", "ads" ),
        "Peremyshlianskyi"        => __( "Peremyshlianskyi", "ads" ),
        "Pustomytivskyi"          => __( "Pustomytivskyi", "ads" ),
        "Radekhivskyi"            => __( "Radekhivskyi", "ads" ),
        "Sambir"                  => __( "Sambir", "ads" ),
        "Sambirskyi"              => __( "Sambirskyi", "ads" ),
        "Skolivskyi"              => __( "Skolivskyi", "ads" ),
        "Sokalskyi"               => __( "Sokalskyi", "ads" ),
        "Starosambirskyi"         => __( "Starosambirskyi", "ads" ),
        "Stryi"                   => __( "Stryi", "ads" ),
        "Stryiskyi"               => __( "Stryiskyi", "ads" ),
        "Truskavets"              => __( "Truskavets", "ads" ),
        "Turkivskyi"              => __( "Turkivskyi", "ads" ),
        "Yavorivskyi"             => __( "Yavorivskyi", "ads" ),
        "Zhovkivskyi"             => __( "Zhovkivskyi", "ads" ),
        "Zhydachivskyi"           => __( "Zhydachivskyi", "ads" ),
        "Zolochivskyi"            => __( "Zolochivskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];