<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Ananivskyi"              => __( "Ananivskyi", "ads" ),
        "Artsyzkyi"               => __( "Artsyzkyi", "ads" ),
        "Baltskyi"                => __( "Baltskyi", "ads" ),
        "Berezivskyi"             => __( "Berezivskyi", "ads" ),
        "Bilhorod-Dnistrovskyi"   => __( "Bilhorod-Dnistrovskyi", "ads" ),
        "Biliaivskyi"             => __( "Biliaivskyi", "ads" ),
        "Bolhradskyi"             => __( "Bolhradskyi", "ads" ),
        "Chernomorsk"             => __( "Chernomorsk", "ads" ),
        "Frunzivskyi"             => __( "Frunzivskyi", "ads" ),
        "Illichivsk"              => __( "Illichivsk", "ads" ),
        "Ivanivskyi"              => __( "Ivanivskyi", "ads" ),
        "Izmail"                  => __( "Izmail", "ads" ),
        "Izmailskyi"              => __( "Izmailskyi", "ads" ),
        "Kiliiskyi"               => __( "Kiliiskyi", "ads" ),
        "Kodymskyi"               => __( "Kodymskyi", "ads" ),
        "Kominternivskyi"         => __( "Kominternivskyi", "ads" ),
        "Kotovsk"                 => __( "Kotovsk", "ads" ),
        "Kotovskyi"               => __( "Kotovskyi", "ads" ),
        "Krasnooknianskyi"        => __( "Krasnooknianskyi", "ads" ),
        "Lyubashivskyi"           => __( "Lyubashivskyi", "ads" ),
        "Mykolaivskyi"            => __( "Mykolaivskyi", "ads" ),
        "Odesa"                   => __( "Odesa", "ads" ),
        "Ovidiopolskyi"           => __( "Ovidiopolskyi", "ads" ),
        "Podilskyi"               => __( "Podilskyi", "ads" ),
        "Reniyskyi"               => __( "Reniyskyi", "ads" ),
        "Rozdilnianskyi"          => __( "Rozdilnianskyi", "ads" ),
        "Saratskyi"               => __( "Saratskyi", "ads" ),
        "Savranskyi"              => __( "Savranskyi", "ads" ),
        "Shyriaivskyi"            => __( "Shyriaivskyi", "ads" ),
        "Tarutynskyi"             => __( "Tarutynskyi", "ads" ),
        "Tatarbunarskyi"          => __( "Tatarbunarskyi", "ads" ),
        "Teplodar"                => __( "Teplodar", "ads" ),
        "Velykomykhailivskyi"     => __( "Velykomykhailivskyi", "ads" ),
        "Yuzhne"                  => __( "Yuzhne", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];