<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Chornukhynskyi"          => __( "Chornukhynskyi", "ads" ),
        "Chutivskyi"              => __( "Chutivskyi", "ads" ),
        "Dykanskyi"               => __( "Dykanskyi", "ads" ),
        "Gorihni plavni"          => __( "Gorihni plavni", "ads" ),
        "Hadiatskyi"              => __( "Hadiatskyi", "ads" ),
        "Hlobynskyi"              => __( "Hlobynskyi", "ads" ),
        "Hrebinkivskyi"           => __( "Hrebinkivskyi", "ads" ),
        "Karlivskyi"              => __( "Karlivskyi", "ads" ),
        "Khorolskyi"              => __( "Khorolskyi", "ads" ),
        "Kobeliatskyi"            => __( "Kobeliatskyi", "ads" ),
        "Komsomolsk"              => __( "Komsomolsk", "ads" ),
        "Kotelevskyi"             => __( "Kotelevskyi", "ads" ),
        "Kozelshchynskyi"         => __( "Kozelshchynskyi", "ads" ),
        "Kremenchuk"              => __( "Kremenchuk", "ads" ),
        "Kremenchutskyi"          => __( "Kremenchutskyi", "ads" ),
        "Lokhvytskyi"             => __( "Lokhvytskyi", "ads" ),
        "Lubenskyi"               => __( "Lubenskyi", "ads" ),
        "Lubny"                   => __( "Lubny", "ads" ),
        "Mashivskyi"              => __( "Mashivskyi", "ads" ),
        "Myrhorod"                => __( "Myrhorod", "ads" ),
        "Myrhorodskyi"            => __( "Myrhorodskyi", "ads" ),
        "Novosanzharskyi"         => __( "Novosanzharskyi", "ads" ),
        "Orzhytskyi"              => __( "Orzhytskyi", "ads" ),
        "Poltava"                 => __( "Poltava", "ads" ),
        "Poltavskyi"              => __( "Poltavskyi", "ads" ),
        "Pyriatynskyi"            => __( "Pyriatynskyi", "ads" ),
        "Reshetylivskyi"          => __( "Reshetylivskyi", "ads" ),
        "Semenivskyi"             => __( "Semenivskyi", "ads" ),
        "Shyshatskyi"             => __( "Shyshatskyi", "ads" ),
        "Velykobahachanskyi"      => __( "Velykobahachanskyi", "ads" ),
        "Zinkivskyi"              => __( "Zinkivskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];