<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopil"                => __( "Ternopil", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];