<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Barskyi"                 => __( "Barskyi", "ads" ),
        "Bershadskyi"             => __( "Bershadskyi", "ads" ),
        "Chechelnytskyi"          => __( "Chechelnytskyi", "ads" ),
        "Chernivetskyi"           => __( "Chernivetskyi", "ads" ),
        "Haisynskyi"              => __( "Haisynskyi", "ads" ),
        "Illinetskyi"             => __( "Illinetskyi", "ads" ),
        "Kalynivskyi"             => __( "Kalynivskyi", "ads" ),
        "Khmilnyk"                => __( "Khmilnyk", "ads" ),
        "Khmilnytskyi"            => __( "Khmilnytskyi", "ads" ),
        "Koziatyn"                => __( "Koziatyn", "ads" ),
        "Koziatynskyi"            => __( "Koziatynskyi", "ads" ),
        "Kryzhopilskyi"           => __( "Kryzhopilskyi", "ads" ),
        "Ladyzhyn"                => __( "Ladyzhyn", "ads" ),
        "Litynskyi"               => __( "Litynskyi", "ads" ),
        "Lypovetskyi"             => __( "Lypovetskyi", "ads" ),
        "Mohyliv-Podilskyi"       => __( "Mohyliv-Podilskyi", "ads" ),
        "Murovanokurylovetskyi"   => __( "Murovanokurylovetskyi", "ads" ),
        "Nemyrivskyi"             => __( "Nemyrivskyi", "ads" ),
        "Orativskyi"              => __( "Orativskyi", "ads" ),
        "Pishchanskyi"            => __( "Pishchanskyi", "ads" ),
        "Pohrebyshchenskyi"       => __( "Pohrebyshchenskyi", "ads" ),
        "Sharhorodskyi"           => __( "Sharhorodskyi", "ads" ),
        "Teplytskyi"              => __( "Teplytskyi", "ads" ),
        "Tomashpilskyi"           => __( "Tomashpilskyi", "ads" ),
        "Trostianetskyi"          => __( "Trostianetskyi", "ads" ),
        "Tulchynskyi"             => __( "Tulchynskyi", "ads" ),
        "Tyvrivskyi"              => __( "Tyvrivskyi", "ads" ),
        "Vinnytsia"               => __( "Vinnytsia", "ads" ),
        "Vinnytskyi"              => __( "Vinnytskyi", "ads" ),
        "Yampilskyi"              => __( "Yampilskyi", "ads" ),
        "Zhmerynka"               => __( "Zhmerynka", "ads" ),
        "Zhmerynskyi"             => __( "Zhmerynskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];