<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Horokhivskyi"            => __( "Horokhivskyi", "ads" ),
        "Ivanychivskyi"           => __( "Ivanychivskyi", "ads" ),
        "Kamin-Kashyrskyi"        => __( "Kamin-Kashyrskyi", "ads" ),
        "Kivertsivskyi"           => __( "Kivertsivskyi", "ads" ),
        "Kovel"                   => __( "Kovel", "ads" ),
        "Kovelskyi"               => __( "Kovelskyi", "ads" ),
        "Lokachynskyi"            => __( "Lokachynskyi", "ads" ),
        "Lutsk"                   => __( "Lutsk", "ads" ),
        "Lutskyi"                 => __( "Lutskyi", "ads" ),
        "Lyubeshivskyi"           => __( "Lyubeshivskyi", "ads" ),
        "Lyubomlskyi"             => __( "Lyubomlskyi", "ads" ),
        "Manevytskyi"             => __( "Manevytskyi", "ads" ),
        "Novovolynsk"             => __( "Novovolynsk", "ads" ),
        "Ratnivskyi"              => __( "Ratnivskyi", "ads" ),
        "Rozhyshchenskyi"         => __( "Rozhyshchenskyi", "ads" ),
        "Shatskyi"                => __( "Shatskyi", "ads" ),
        "Starovyzhivskyi"         => __( "Starovyzhivskyi", "ads" ),
        "Turiiskyi"               => __( "Turiiskyi", "ads" ),
        "Volodymyr-Volynskyi"     => __( "Volodymyr-Volynskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];