<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Berehivskyi"             => __( "Berehivskyi", "ads" ),
        "Berehove"                => __( "Berehove", "ads" ),
        "Chop"                    => __( "Chop", "ads" ),
        "Irshavskyi"              => __( "Irshavskyi", "ads" ),
        "Khust"                   => __( "Khust", "ads" ),
        "Khustskyi"               => __( "Khustskyi", "ads" ),
        "Mizhhirskyi"             => __( "Mizhhirskyi", "ads" ),
        "Mukacheve"               => __( "Mukacheve", "ads" ),
        "Mukachivskyi"            => __( "Mukachivskyi", "ads" ),
        "Perechynskyi"            => __( "Perechynskyi", "ads" ),
        "Rakhivskyi"              => __( "Rakhivskyi", "ads" ),
        "Svaliavskyi"             => __( "Svaliavskyi", "ads" ),
        "Tyachivskyi"             => __( "Tyachivskyi", "ads" ),
        "Uzhhorod"                => __( "Uzhhorod", "ads" ),
        "Uzhhorodskyi"            => __( "Uzhhorodskyi", "ads" ),
        "Velykobereznianskyi"     => __( "Velykobereznianskyi", "ads" ),
        "Volovetskyi"             => __( "Volovetskyi", "ads" ),
        "Vynohradivskyi"          => __( "Vynohradivskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];