<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Berdiansk"               => __( "Berdiansk", "ads" ),
        "Berdianskyi"             => __( "Berdianskyi", "ads" ),
        "Chernihivskyi"           => __( "Chernihivskyi", "ads" ),
        "Enerhodar"               => __( "Enerhodar", "ads" ),
        "Huliaipilskyi"           => __( "Huliaipilskyi", "ads" ),
        "Kamiansko-Dniprovskyi"   => __( "Kamiansko-Dniprovskyi", "ads" ),
        "Kuibyshevskyi"           => __( "Kuibyshevskyi", "ads" ),
        "Melitopol"               => __( "Melitopol", "ads" ),
        "Melitopolskyi"           => __( "Melitopolskyi", "ads" ),
        "Mykhailivskyi"           => __( "Mykhailivskyi", "ads" ),
        "Novomykolaivskyi"        => __( "Novomykolaivskyi", "ads" ),
        "Orikhivskyi"             => __( "Orikhivskyi", "ads" ),
        "Polohivskyi"             => __( "Polohivskyi", "ads" ),
        "Pryazovskyi"             => __( "Pryazovskyi", "ads" ),
        "Prymorskyi"              => __( "Prymorskyi", "ads" ),
        "Rozivskyi"               => __( "Rozivskyi", "ads" ),
        "Tokmak"                  => __( "Tokmak", "ads" ),
        "Tokmatskyi"              => __( "Tokmatskyi", "ads" ),
        "Vasylivskyi"             => __( "Vasylivskyi", "ads" ),
        "Velykobilozerskyi"       => __( "Velykobilozerskyi", "ads" ),
        "Veselivskyi"             => __( "Veselivskyi", "ads" ),
        "Vilnianskyi"             => __( "Vilnianskyi", "ads" ),
        "Yakymivskyi"             => __( "Yakymivskyi", "ads" ),
        "Zaporizhzhia"            => __( "Zaporizhzhia", "ads" ),
        "Zaporizkyi"              => __( "Zaporizkyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];