<?php
    
    return [
        
        "Piatykhatskyi"           => __( "Piatykhatskyi", "ads" ),
        "Marinskyi"               => __( "Marinskyi", "ads" ),
        "Kupianskyi"              => __( "Kupianskyi", "ads" ),
        "Khmelnytskyi"            => __( "Khmelnytskyi", "ads" ),
        "Pereiaslav-Khmelnytskyi" => __( "Pereiaslav-Khmelnytskyi", "ads" ),
        "Slovianoserbskyi"        => __( "Slovianoserbskyi", "ads" ),
        "Berezhanskyi"            => __( "Berezhanskyi", "ads" ),
        "Borshchivskyi"           => __( "Borshchivskyi", "ads" ),
        "Buchatskyi"              => __( "Buchatskyi", "ads" ),
        "Chortkivskyi"            => __( "Chortkivskyi", "ads" ),
        "Husiatynskyi"            => __( "Husiatynskyi", "ads" ),
        "Kozivskyi"               => __( "Kozivskyi", "ads" ),
        "Kremenetskyi"            => __( "Kremenetskyi", "ads" ),
        "Lanovetskyi"             => __( "Lanovetskyi", "ads" ),
        "Monastyryskyi"           => __( "Monastyryskyi", "ads" ),
        "Pidhaietskyi"            => __( "Pidhaietskyi", "ads" ),
        "Pidvolochyskyi"          => __( "Pidvolochyskyi", "ads" ),
        "Shumskyi"                => __( "Shumskyi", "ads" ),
        "Terebovlianskyi"         => __( "Terebovlianskyi", "ads" ),
        "Ternopilskyi"            => __( "Ternopilskyi", "ads" ),
        "Zalishchytskyi"          => __( "Zalishchytskyi", "ads" ),
        "Zbarazkyi"               => __( "Zbarazkyi", "ads" ),
        "Zborivskyi"              => __( "Zborivskyi", "ads" ),
        "Andrushivskyi"           => __( "Andrushivskyi", "ads" ),
        "Baranivskyi"             => __( "Baranivskyi", "ads" ),
        "Berdychiv"               => __( "Berdychiv", "ads" ),
        "Berdychivskyi"           => __( "Berdychivskyi", "ads" ),
        "Brusylivskyi"            => __( "Brusylivskyi", "ads" ),
        "Cherniakhivskyi"         => __( "Cherniakhivskyi", "ads" ),
        "Chervonoarmiyskyi"       => __( "Chervonoarmiyskyi", "ads" ),
        "Chudnivskyi"             => __( "Chudnivskyi", "ads" ),
        "Korosten"                => __( "Korosten", "ads" ),
        "Korostenskyi"            => __( "Korostenskyi", "ads" ),
        "Korostyshivskyi"         => __( "Korostyshivskyi", "ads" ),
        "Luhynskyi"               => __( "Luhynskyi", "ads" ),
        "Lyubarskyi"              => __( "Lyubarskyi", "ads" ),
        "Malyn"                   => __( "Malyn", "ads" ),
        "Malynskyi"               => __( "Malynskyi", "ads" ),
        "Narodytskyi"             => __( "Narodytskyi", "ads" ),
        "Novohrad-Volynskyi"      => __( "Novohrad-Volynskyi", "ads" ),
        "Olevskyi"                => __( "Olevskyi", "ads" ),
        "Ovrutskyi"               => __( "Ovrutskyi", "ads" ),
        "Popilnianskyi"           => __( "Popilnianskyi", "ads" ),
        "Radomyshlskyi"           => __( "Radomyshlskyi", "ads" ),
        "Romanivskyi"             => __( "Romanivskyi", "ads" ),
        "Ruzhynskyi"              => __( "Ruzhynskyi", "ads" ),
        "Volodarsko-Volynskyi"    => __( "Volodarsko-Volynskyi", "ads" ),
        "Yemilchynskyi"           => __( "Yemilchynskyi", "ads" ),
        "Zhytomyr"                => __( "Zhytomyr", "ads" ),
        "Zhytomyrskyi"            => __( "Zhytomyrskyi", "ads" ),
        "Other"                   => __( "Other", "ads" ),
    
    ];