<?php
    
    return [
        
        "Bangkalan"   => __( "Bangkalan", "ads" ),
        "Banyuwangi"  => __( "Banyuwangi", "ads" ),
        "Batu"        => __( "Batu", "ads" ),
        "Blitar"      => __( "Blitar", "ads" ),
        "Bojonegoro"  => __( "Bojonegoro", "ads" ),
        "Bondowoso"   => __( "Bondowoso", "ads" ),
        "Caruban"     => __( "Caruban", "ads" ),
        "Gresik"      => __( "Gresik", "ads" ),
        "Jember"      => __( "Jember", "ads" ),
        "Jombang"     => __( "Jombang", "ads" ),
        "Kanigoro"    => __( "Kanigoro", "ads" ),
        "Kediri"      => __( "Kediri", "ads" ),
        "Kediri"      => __( "Kediri", "ads" ),
        "Kepanjen"    => __( "Kepanjen", "ads" ),
        "Kraksaan"    => __( "Kraksaan", "ads" ),
        "Lamongan"    => __( "Lamongan", "ads" ),
        "Lumajang"    => __( "Lumajang", "ads" ),
        "Madiun"      => __( "Madiun", "ads" ),
        "Magetan"     => __( "Magetan", "ads" ),
        "Malang"      => __( "Malang", "ads" ),
        "Mojokerto"   => __( "Mojokerto", "ads" ),
        "Mojokerto"   => __( "Mojokerto", "ads" ),
        "Nganjuk"     => __( "Nganjuk", "ads" ),
        "Ngawi"       => __( "Ngawi", "ads" ),
        "Pacitan"     => __( "Pacitan", "ads" ),
        "Pasuruan"    => __( "Pasuruan", "ads" ),
        "Pemekasan"   => __( "Pemekasan", "ads" ),
        "Ponogoro"    => __( "Ponogoro", "ads" ),
        "Probolinggo" => __( "Probolinggo", "ads" ),
        "Sampang"     => __( "Sampang", "ads" ),
        "Sidoarjo"    => __( "Sidoarjo", "ads" ),
        "Situbondo"   => __( "Situbondo", "ads" ),
        "Sumenep"     => __( "Sumenep", "ads" ),
        "Surabaya"    => __( "Surabaya", "ads" ),
        "Trenggalek"  => __( "Trenggalek", "ads" ),
        "Tuban"       => __( "Tuban", "ads" ),
        "Tulungagung" => __( "Tulungagung", "ads" ),
    
    ];