<?php
    
    return [
        
        "Banjarnegara" => __( "Banjarnegara", "ads" ),
        "Batang"       => __( "Batang", "ads" ),
        "Blora"        => __( "Blora", "ads" ),
        "Boyolali"     => __( "Boyolali", "ads" ),
        "Brebes"       => __( "Brebes", "ads" ),
        "Cilacap"      => __( "Cilacap", "ads" ),
        "Demak"        => __( "Demak", "ads" ),
        "Jepara"       => __( "Jepara", "ads" ),
        "Kajen"        => __( "Kajen", "ads" ),
        "Karanganyar"  => __( "Karanganyar", "ads" ),
        "Kebumen"      => __( "Kebumen", "ads" ),
        "Kendal"       => __( "Kendal", "ads" ),
        "Klaten"       => __( "Klaten", "ads" ),
        "Kudus"        => __( "Kudus", "ads" ),
        "Magelang"     => __( "Magelang", "ads" ),
        "Mungkid"      => __( "Mungkid", "ads" ),
        "Pati"         => __( "Pati", "ads" ),
        "Pekalongan"   => __( "Pekalongan", "ads" ),
        "Pemalang"     => __( "Pemalang", "ads" ),
        "Purbalingga"  => __( "Purbalingga", "ads" ),
        "Purwodadi"    => __( "Purwodadi", "ads" ),
        "Purwokerto"   => __( "Purwokerto", "ads" ),
        "Purworejo"    => __( "Purworejo", "ads" ),
        "Rembang"      => __( "Rembang", "ads" ),
        "Salatiga"     => __( "Salatiga", "ads" ),
        "Semarang"     => __( "Semarang", "ads" ),
        "Slawi"        => __( "Slawi", "ads" ),
        "Sragen"       => __( "Sragen", "ads" ),
        "Sukoharjo"    => __( "Sukoharjo", "ads" ),
        "Surakarta"    => __( "Surakarta", "ads" ),
        "Tegal"        => __( "Tegal", "ads" ),
        "Temanggung"   => __( "Temanggung", "ads" ),
        "Ungaran"      => __( "Ungaran", "ads" ),
        "Wonogiri"     => __( "Wonogiri", "ads" ),
        "Wonosobo"     => __( "Wonosobo", "ads" ),
    
    ];