<?php
    
    return [
        
        "Kediri"           => __( "Kediri", "ads" ),
        "Mojokerto"        => __( "Mojokerto", "ads" ),
        "Aekkanopan"       => __( "Aekkanopan", "ads" ),
        "Balige"           => __( "Balige", "ads" ),
        "Binjai"           => __( "Binjai", "ads" ),
        "Dolok Sanggul"    => __( "Dolok Sanggul", "ads" ),
        "Gunung Sitoli"    => __( "Gunung Sitoli", "ads" ),
        "Gunung Tua"       => __( "Gunung Tua", "ads" ),
        "Gunungsitoli"     => __( "Gunungsitoli", "ads" ),
        "Kabanjahe"        => __( "Kabanjahe", "ads" ),
        "Kota Pinang"      => __( "Kota Pinang", "ads" ),
        "Lima Puluh"       => __( "Lima Puluh", "ads" ),
        "Lolofaoso"        => __( "Lolofaoso", "ads" ),
        "Lubuk Pakam"      => __( "Lubuk Pakam", "ads" ),
        "Medan"            => __( "Medan", "ads" ),
        "Onolimbu"         => __( "Onolimbu", "ads" ),
        "Padang Sidempuan" => __( "Padang Sidempuan", "ads" ),
        "Pandan"           => __( "Pandan", "ads" ),
        "Pangururan"       => __( "Pangururan", "ads" ),
        "Panyabungan"      => __( "Panyabungan", "ads" ),
        "Pematang Raya"    => __( "Pematang Raya", "ads" ),
        "Pematang Siantar" => __( "Pematang Siantar", "ads" ),
        "Rantau Prapat"    => __( "Rantau Prapat", "ads" ),
        "Salak"            => __( "Salak", "ads" ),
        "Sei Rampah"       => __( "Sei Rampah", "ads" ),
        "Sibolga"          => __( "Sibolga", "ads" ),
        "Sibuhuan"         => __( "Sibuhuan", "ads" ),
        "Sidikalang"       => __( "Sidikalang", "ads" ),
        "Sipirok"          => __( "Sipirok", "ads" ),
        "Stabat"           => __( "Stabat", "ads" ),
        "Tanjung Balai"    => __( "Tanjung Balai", "ads" ),
        "Tarutung"         => __( "Tarutung", "ads" ),
        "Tebing Tinggi"    => __( "Tebing Tinggi", "ads" ),
        "Teluk Dalam"      => __( "Teluk Dalam", "ads" ),
    
    ];