<?php
    
    return [
        
        "Ahırlı"     => __( "Ahırlı", "ads" ),
        "Akören"     => __( "Akören", "ads" ),
        "Akşehir"    => __( "Akşehir", "ads" ),
        "Altınekin"  => __( "Altınekin", "ads" ),
        "Beyşehir"   => __( "Beyşehir", "ads" ),
        "Bozkır"     => __( "Bozkır", "ads" ),
        "Cihanbeyli" => __( "Cihanbeyli", "ads" ),
        "Derbent"    => __( "Derbent", "ads" ),
        "Derebucak"  => __( "Derebucak", "ads" ),
        "Doğanhisar" => __( "Doğanhisar", "ads" ),
        "Emirgazi"   => __( "Emirgazi", "ads" ),
        "Ereğli"     => __( "Ereğli", "ads" ),
        "Güneysınır" => __( "Güneysınır", "ads" ),
        "Hadim"      => __( "Hadim", "ads" ),
        "Halkapınar" => __( "Halkapınar", "ads" ),
        "Hüyük"      => __( "Hüyük", "ads" ),
        "Ilgın"      => __( "Ilgın", "ads" ),
        "Kadınhanı"  => __( "Kadınhanı", "ads" ),
        "Karapınar"  => __( "Karapınar", "ads" ),
        "Karatay"    => __( "Karatay", "ads" ),
        "Kulu"       => __( "Kulu", "ads" ),
        "Meram"      => __( "Meram", "ads" ),
        "Sarayönü"   => __( "Sarayönü", "ads" ),
        "Selçuklu"   => __( "Selçuklu", "ads" ),
        "Seydişehir" => __( "Seydişehir", "ads" ),
        "Taşkent"    => __( "Taşkent", "ads" ),
        "Tuzlukçu"   => __( "Tuzlukçu", "ads" ),
        "Yalıhöyük"  => __( "Yalıhöyük", "ads" ),
        "Yunak"      => __( "Yunak", "ads" ),
        "Çeltik"     => __( "Çeltik", "ads" ),
        "Çumra"      => __( "Çumra", "ads" ),
        "Other"      => __( "Other", "ads" ),
    
    ];