<?php
    
    return [
        
        "Codegua"           => __( "Codegua", "ads" ),
        "Coinco"            => __( "Coinco", "ads" ),
        "Coltauco"          => __( "Coltauco", "ads" ),
        "Doñihue"           => __( "Doñihue", "ads" ),
        "Graneros"          => __( "Graneros", "ads" ),
        "Las Cabras"        => __( "Las Cabras", "ads" ),
        "Machalí"           => __( "Machalí", "ads" ),
        "Malloa"            => __( "Malloa", "ads" ),
        "Mostazal"          => __( "Mostazal", "ads" ),
        "Olivar"            => __( "Olivar", "ads" ),
        "Peumo"             => __( "Peumo", "ads" ),
        "Pichidegua"        => __( "Pichidegua", "ads" ),
        "Quinta de Tilcoco" => __( "Quinta de Tilcoco", "ads" ),
        "Rancagua"          => __( "Rancagua", "ads" ),
        "Rengo"             => __( "Rengo", "ads" ),
        "Requínoa"          => __( "Requínoa", "ads" ),
        "San Vicente"       => __( "San Vicente", "ads" ),
        "La Estrella"       => __( "La Estrella", "ads" ),
        "Litueche"          => __( "Litueche", "ads" ),
        "Marchigüe"         => __( "Marchigüe", "ads" ),
        "Navidad"           => __( "Navidad", "ads" ),
        "Paredones"         => __( "Paredones", "ads" ),
        "Pichilemu"         => __( "Pichilemu", "ads" ),
        "Chimbarongo"       => __( "Chimbarongo", "ads" ),
        "Chépica"           => __( "Chépica", "ads" ),
        "Lolol"             => __( "Lolol", "ads" ),
        "Nancagua"          => __( "Nancagua", "ads" ),
        "Palmilla"          => __( "Palmilla", "ads" ),
        "Peralillo"         => __( "Peralillo", "ads" ),
        "Placilla"          => __( "Placilla", "ads" ),
        "Pumanque"          => __( "Pumanque", "ads" ),
        "San Fernando"      => __( "San Fernando", "ads" ),
        "Santa Cruz"        => __( "Santa Cruz", "ads" ),
        "Other"             => __( "Other", "ads" ),
    
    ];