<?php
    
    return [
        
        "Colina"              => __( "Colina", "ads" ),
        "Lampa"               => __( "Lampa", "ads" ),
        "Tiltil"              => __( "Tiltil", "ads" ),
        "Pirque"              => __( "Pirque", "ads" ),
        "Puente Alto"         => __( "Puente Alto", "ads" ),
        "San José de Maipo"   => __( "San José de Maipo", "ads" ),
        "Buin"                => __( "Buin", "ads" ),
        "Calera de Tango"     => __( "Calera de Tango", "ads" ),
        "Paine"               => __( "Paine", "ads" ),
        "San Bernardo"        => __( "San Bernardo", "ads" ),
        "Alhué"               => __( "Alhué", "ads" ),
        "Curacaví"            => __( "Curacaví", "ads" ),
        "María Pinto"         => __( "María Pinto", "ads" ),
        "Melipilla"           => __( "Melipilla", "ads" ),
        "San Pedro"           => __( "San Pedro", "ads" ),
        "Cerrillos"           => __( "Cerrillos", "ads" ),
        "Cerro Navia"         => __( "Cerro Navia", "ads" ),
        "Conchalí"            => __( "Conchalí", "ads" ),
        "El Bosque"           => __( "El Bosque", "ads" ),
        "Estación Central"    => __( "Estación Central", "ads" ),
        "Huechuraba"          => __( "Huechuraba", "ads" ),
        "Independencia"       => __( "Independencia", "ads" ),
        "La Cisterna"         => __( "La Cisterna", "ads" ),
        "La Florida"          => __( "La Florida", "ads" ),
        "La Granja"           => __( "La Granja", "ads" ),
        "La Pintana"          => __( "La Pintana", "ads" ),
        "La Reina"            => __( "La Reina", "ads" ),
        "Las Condes"          => __( "Las Condes", "ads" ),
        "Lo Barnechea"        => __( "Lo Barnechea", "ads" ),
        "Lo Espejo"           => __( "Lo Espejo", "ads" ),
        "Lo Prado"            => __( "Lo Prado", "ads" ),
        "Macul"               => __( "Macul", "ads" ),
        "Maipú"               => __( "Maipú", "ads" ),
        "Pedro Aguirre Cerda" => __( "Pedro Aguirre Cerda", "ads" ),
        "Peñalolén"           => __( "Peñalolén", "ads" ),
        "Providencia"         => __( "Providencia", "ads" ),
        "Pudahuel"            => __( "Pudahuel", "ads" ),
        "Quilicura"           => __( "Quilicura", "ads" ),
        "Quinta Normal"       => __( "Quinta Normal", "ads" ),
        "Recoleta"            => __( "Recoleta", "ads" ),
        "Renca"               => __( "Renca", "ads" ),
        "San Joaquín"         => __( "San Joaquín", "ads" ),
        "San Miguel"          => __( "San Miguel", "ads" ),
        "San Ramón"           => __( "San Ramón", "ads" ),
        "Vitacura"            => __( "Vitacura", "ads" ),
        "santiago centro"     => __( "santiago centro", "ads" ),
        "Ñuñoa"               => __( "Ñuñoa", "ads" ),
        "El Monte"            => __( "El Monte", "ads" ),
        "Isla de Maipo"       => __( "Isla de Maipo", "ads" ),
        "Padre Hurtado"       => __( "Padre Hurtado", "ads" ),
        "Peñaflor"            => __( "Peñaflor", "ads" ),
        "Talagante"           => __( "Talagante", "ads" ),
        "Other"               => __( "Other", "ads" ),
    
    ];